spring:
  application:
    name: stock-dividend-api

  h2:
    console:
      enabled: true
      path: /h2-console

  jpa:
    hibernate:
      ddl-auto: create
      use-new-id-generator-mappings: false
    show-sql: true
    defer-datasource-initialization: true

  datasource:
    driver-class-name: org.h2.Driver
    url: jdbc:h2:mem:stockdividendapi;DB_CLOSE_DELAY=-1
    username: sa
    password:

  redis:
    host: localhost
    port: 6379

  jwt:
    secret: b3hhaGV4LXN0b2NrLWRpdmlkZW5kLWFwaS1zZWNyZXQta2V5Cg==


scheduler:
  scrap:
    yahoo: "0 0 0 * * *"